apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: erp
spec:
  replicas: 2 # Adjust as needed
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: frappe/erpnext-worker:${SOFTWARE_VERSION_TAG}
          restartPolicy: Always
          volumeMounts:
            - name: sites-volume
              mountPath: /home/frappe/frappe-bench/sites
            - name: assets-volume
              mountPath: /home/frappe/frappe-bench/sites/assets