apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurator-deployment
  namespace: erp
spec:
  selector:
    matchLabels:
      app: configurator
  template:
    metadata:
      labels:
        app: configurator
    spec:
      restartPolicy: OnFailure
      containers:
        - name: configurator
          image: frappe/erpnext-worker:${SOFTWARE_VERSION_TAG}
          command: ["python", "configure.py"]
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: db-port
            - name: REDIS_CACHE
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: redis-cache
            - name: REDIS_QUEUE
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: redis-queue
            - name: REDIS_SOCKETIO
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: redis-socket
            - name: SOCKETIO_PORT
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: socket-port
          volumeMounts:
            - name: sites-volume
              mountPath: /home/frappe/frappe-bench/sites