apiVersion: batch/v1
kind: Job
metadata:
  name: create-site-job
  namespace: erp
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-site
          image: frappe/erpnext-worker:latest
          command: ["bash", "-c"]
          args:
            - >
              set -e;
              until nc -z -w 5 ${DB_HOST} 3306; do echo "Waiting for DB..."; sleep 5; done;
              until nc -z -w 5 ${REDIS_CACHE} 6379; do echo "Waiting for Redis Cache..."; sleep 5; done;
              until nc -z -w 5 ${REDIS_QUEUE} 6379; do echo "Waiting for Redis Queue..."; sleep 5; done;
              until nc -z -w 5 ${REDIS_SOCKETIO} ${SOCKETIO_PORT}; do echo "Waiting for Redis SocketIO..."; sleep 5; done;
              echo "Dependencies ready";
              bench new-site frontend --admin-password=${ADMIN_PASSWORD} --db-root-password=${MYSQL_ROOT_PASSWORD} --install-app payments --install-app erpnext --set-default;
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: erpnext-secrets
                  key: mysql-root-password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: erpnext-secrets
                  key: admin-password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: db-port
            - name: REDIS_CACHE
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: redis-cache
            - name: REDIS_QUEUE
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: redis-queue
            - name: REDIS_SOCKETIO
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: redis-socket
            - name: SOCKETIO_PORT
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: socket-port
          volumeMounts:
            - name: sites-volume
              mountPath: /home/frappe/frappe-bench/sites
            - name: assets-volume
              mountPath: /home/frappe/frappe-bench/sites/assets
      volumes:
        - name: sites-volume
          persistentVolumeClaim:
            claimName: sites-pvc
        - name: assets-volume
          persistentVolumeClaim:
            claimName: assets-pvc