apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: erp
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      restartPolicy: Always
      containers:
        - name: db
          image: mariadb:10.6
          #command:
          #  - "mariadbd"  # The MariaDB server executable
          #  - "--character-set-server=utf8mb4"
          #    - "--collation-server=utf8mb4_unicode_ci"
          #    - "--skip-character-set-client-handshake"
          #  - "--skip-innodb-read-only-compressed"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: erpnext-secrets
                  key: mysql-root-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data-volume
          persistentVolumeClaim:
            claimName: sites-pvc