apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: erp
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      containers:
        - name: frontend
          image: frappe/erpnext-nginx:latest
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: backend-host
            - name: FRAPPE_SITE_NAME_HEADER
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: frappe-header
            - name: SOCKETIO
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: socket-io
            - name: UPSTREAM_REAL_IP_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: uppstream-ip
            - name: UPSTREAM_REAL_IP_HEADER
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: uppstream-header
            - name: UPSTREAM_REAL_IP_RECURSIVE
              valueFrom:
                secretKeyRef:
                  name: erpnext-configs
                  key: uppstream-recursive
          volumeMounts:
            - name: sites-volume
              mountPath: /usr/share/nginx/html/sites
            - name: assets-volume
              mountPath: /usr/share/nginx/html/assets
      volumes:
        - name: sites-volume
          persistentVolumeClaim:
            claimName: sites-pvc
        - name: assets-volume
          persistentVolumeClaim:
            claimName: assets-pvc