apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-long-deployment
  namespace: erp
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: queue-long
  template:
    metadata:
      labels:
        app: queue-long
    spec:
      restartPolicy: Always
      containers:
        - name: queue-long
          image: frappe/erpnext-worker:latest
          command: ["bench", "worker", "--queue", "long"]
          volumeMounts:
            - name: sites-volume
              mountPath: /home/frappe/frappe-bench/sites
            - name: assets-volume
              mountPath: /home/frappe/frappe-bench/sites/assets
      volumes:
        - name: sites-volume
          persistentVolumeClaim:
            claimName: sites-pvc
        - name: assets-volume
          persistentVolumeClaim:
            claimName: assets-pvc