apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache-deployment
  namespace: erp
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      restartPolicy: Always
      containers:
        - name: redis-cache
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-cache-data-volume
              mountPath: /data
      volumes:
        - name: redis-cache-data-volume
          persistentVolumeClaim:
            claimName: redis-cache-data-pvc