apiVersion: v1
kind: ConfigMap
metadata:
  name: erpnext-configs
  namespace: erp
data:
  db-host: "db-service"
  db-port: "3306"
  redis-cache: "redis-cache-service:6379"
  redis-queue: "redis-queue-service:6379"
  redis-socket: "redis-socketio-service:6379"
  socket-port: "9000"
  socket-io: "websocket-service:9000"
  backend-host: "backend-service:8000"
  frappe-header: "X-Frappe-Site-Name"
  uppstream-ip: "198.7.119.0"
  uppstream-header: "X-Forwarded-For"
  uppstream-recursive: "on"