#!/bin/bash
source .env
kubectl apply -f namespace.yaml
kubectl apply -f secrets.yaml
kubectl apply -f configs.yaml
kubectl apply -f assets-pv.yaml
kubectl apply -f assets-pvc.yaml
kubectl apply -f db-data-pv.yaml
kubectl apply -f db-data-pvc.yaml
kubectl apply -f redis-cache-data-pv.yaml
kubectl apply -f redis-cache-data-pvc.yaml
kubectl apply -f redis-queue-data-pv.yaml
kubectl apply -f redis-queue-data-pvc.yaml
kubectl apply -f redis-socketio-data-pv.yaml
kubectl apply -f redis-socketio-data-pvc.yaml
kubectl apply -f sites-pv.yaml
kubectl apply -f sites-pvc.yaml
kubectl apply -f backend-deployment.yaml
kubectl apply -f configurator-deployment.yaml
kubectl apply -f create-site-job.yaml
kubectl apply -f db-deployment.yaml
kubectl apply -f frontend-deployment.yaml
kubectl apply -f queue-default-deployment.yaml
kubectl apply -f queue-long-deployment.yaml
kubectl apply -f queue-short-deployment.yaml
kubectl apply -f redis-cache-deployment.yaml
kubectl apply -f redis-queue-deployment.yaml
kubectl apply -f redis-socketio-deployment.yaml
kubectl apply -f scheduler-deployment.yaml
kubectl apply -f websocket-deployment.yaml
kubectl apply -f  db-service.yaml
kubectl apply -f redis-cache-service.yaml
kubectl apply -f redis-queue-service.yaml
kubectl apply -f redis-socketio-service.yaml
kubectl apply -f websocket-service.yaml
kubectl apply -f backend-service.yaml
kubectl apply -f frontend-service.yaml