apiVersion: v1
kind: PersistentVolume
metadata:
  name: assets-pv
  namespace: erp
spec:
  capacity:
    storage: 10Gi # Adjust as needed
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany, depending on your needs
  persistentVolumeReclaimPolicy: Retain # Or Delete
  hostPath:
    path: ${PWD}/assets # Adjust to your actual host path