apiVersion: v1
kind: PersistentVolume
metadata:
  name: assets-pv
  namespace: erp
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName:  my-nfs-storage
  hostPath:
    path: /mnt/erp/assets
    type: Directory