apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets-pvc
  namespace: erp
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 10Gi 
  storageClassName:  my-nfs-storage
  volumeName: assets-pv