apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-pv
  namespace: erp
spec:
  capacity:
    storage: 20Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  storageClassName:  my-nfs-storage
  hostPath:
    path: /mnt/erp/db-data
    # type: Directory