apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-pv
  namespace: erp
spec:
  capacity:
    storage: 20Gi # Adjust as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Or Delete
  hostPath:
    path: /mnt/erp/db-data # Adjust to your actual host path
    type: Directory