apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-queue-data-pv
  namespace: erp
spec:
  capacity:
    storage: 5Gi # Adjust as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Or Delete
  hostPath:
    path: /mnt/erp/redis-queue-data # Adjust to your actual host path
    type: Directory