apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-queue-data-pvc
  namespace: erp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName:  my-nfs-storage
  volumeName: redis-queue-data-pv # Remove this if you are using a StorageClass