apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-socketio-data-pv
  namespace: erp
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  storageClassName:  my-nfs-storage
  hostPath:
    path: /mnt/erp/redis-socketio-data
    # type: Directory