apiVersion: v1
kind: PersistentVolume
metadata:
  name: sites-pv
  namespace: erp
spec:
  capacity:
    storage: 10Gi # Adjust as needed
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany, depending on your needs
  persistentVolumeReclaimPolicy: Retain # Or Delete
  storageClassName:  my-nfs-storage
  hostPath:
    path: /mnt/erp/sites # Adjust to your actual host path
    type: Directory