apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sites-pvc
  namespace: erp
spec:
  accessModes:
    - ReadWriteMany # Must match the PV access mode
  resources:
    requests:
      storage: 10Gi # Must match the PV capacity
  storageClassName:  my-nfs-storage
  volumeName: sites-pv # Remove this if you are using a StorageClass