apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sites-pvc
  namespace: erp
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 10Gi 
  storageClassName:  my-nfs-storage
  volumeName: sites-pv # Remove this if you are using a StorageClass