apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: erp
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # Standard HTTP port
      targetPort: 9999
  type: LoadBalancer # Or NodePort if you're not using a cloud load balancer