apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: erp
spec:
  selector:
    app: websocket
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000 # The container port
  type: ClusterIP